-- Run this in your Supabase Dashboard -> SQL Editor

ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'CAT';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'TOPICAL';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'ZONE';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'SUB_COUNTY';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'COUNTY';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'REGIONAL';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'PRE_MOCK';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'MOCK';
ALTER TYPE exam_type ADD VALUE IF NOT EXISTS 'POST_MOCK';
