import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseAdmin } from '@/lib/supabase-admin';
import { parseStkCallback, type StkCallbackBody } from '@/lib/mpesa';
import { verifyWebhookToken } from '@/lib/crypto';

export const runtime = 'nodejs';

/**
 * Safaricom calls this directly — there is no Clerk session, and Daraja
 * callbacks aren't cryptographically signed. Two safeguards gate the write:
 * the per-school webhook token in the URL (generated by us, known only to
 * Safaricom via the registered callback URL), and the CheckoutRequestID
 * matching a PENDING payment for this school. The token matters because the
 * payer themselves learns their own CheckoutRequestID from the initiate
 * response — without the token, they could forge a "success" callback for
 * a prompt they cancelled. For further hardening, also allowlist
 * Safaricom's callback IP ranges at the reverse proxy / WAF level.
 *
 * Once verified, always resolves 200 quickly — Safaricom retries
 * aggressively on anything else, so failures are logged and swallowed
 * rather than surfaced to it. Forged requests (bad token) get a plain 403.
 */
export async function POST(request: NextRequest, { params }: { params: Promise<{ schoolId: string; token: string }> }) {
    const { schoolId, token } = await params;
    try {
        const supabase = createSupabaseAdmin();

        const { data: settings } = await supabase
            .from('school_payment_settings')
            .select('webhook_token')
            .eq('school_id', schoolId)
            .maybeSingle();

        if (!verifyWebhookToken(token, settings?.webhook_token)) {
            console.error('[mpesa callback] webhook token mismatch for school', schoolId);
            return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
        }

        const body = (await request.json()) as StkCallbackBody;
        const parsed = parseStkCallback(body);
        if (!parsed) {
            console.error('[mpesa callback] unrecognized payload', JSON.stringify(body));
            return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
        }

        const { data: payment } = await supabase
            .from('fee_payments')
            .select('id, status, school_id, amount')
            .eq('mpesa_checkout_request_id', parsed.checkoutRequestId)
            .maybeSingle();

        if (!payment || payment.school_id !== schoolId) {
            console.error('[mpesa callback] no matching pending payment', parsed.checkoutRequestId, schoolId);
            return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
        }
        if (payment.status !== 'PENDING') {
            // Already processed (Safaricom's retry) — no-op.
            return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
        }

        if (parsed.success) {
            await supabase
                .from('fee_payments')
                .update({
                    status: 'COMPLETED',
                    amount: parsed.amount ?? payment.amount,
                    mpesa_receipt_number: parsed.mpesaReceiptNumber || null,
                    phone_number: parsed.phoneNumber || undefined,
                    paid_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                })
                .eq('id', payment.id);
        } else {
            await supabase
                .from('fee_payments')
                .update({
                    status: 'FAILED',
                    notes: parsed.resultDesc,
                    updated_at: new Date().toISOString(),
                })
                .eq('id', payment.id);
        }

        return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
    } catch (err) {
        console.error('[mpesa callback] error processing callback for school', schoolId, err);
        return NextResponse.json({ ResultCode: 0, ResultDesc: 'Accepted' });
    }
}
