import React from 'react';
import { Document, Page, View, Text, StyleSheet, renderToBuffer } from '@react-pdf/renderer';

const NAVY = '#1A365D';
const GRAY_200 = '#E2E6ED';
const GRAY_400 = '#9CA3AF';
const GRAY_700 = '#374151';
const LIGHT = '#F2F2F2';
const GREEN = '#166534';

export interface ExamResultsPdfRow {
    position: number;
    studentName: string;
    admissionNumber: string;
    marks: string;
    grade: string;
    remarks?: string;
}

export interface ExamResultsPdfData {
    schoolName: string;
    examName: string;
    subjectName: string;
    className: string;
    maxScore: number;
    generatedAt: string;
    rows: ExamResultsPdfRow[];
}

const st = StyleSheet.create({
    page: { paddingTop: 28, paddingBottom: 36, paddingHorizontal: 32, fontFamily: 'Helvetica', fontSize: 9, color: GRAY_700 },
    schoolName: { fontSize: 15, fontFamily: 'Helvetica-Bold', color: NAVY, textTransform: 'uppercase', letterSpacing: 0.5 },
    docTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: GRAY_700, marginTop: 6 },
    subTitle: { fontSize: 9, color: GRAY_400, marginTop: 2, marginBottom: 12 },
    table: { borderWidth: 1, borderColor: GRAY_200, borderRadius: 2 },
    headerRow: { flexDirection: 'row', backgroundColor: NAVY, paddingVertical: 6 },
    row: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: GRAY_200, paddingVertical: 5 },
    rowAlt: { backgroundColor: LIGHT },
    colPos: { width: '10%', paddingHorizontal: 6, color: 'white', fontFamily: 'Helvetica-Bold' },
    colName: { width: '38%', paddingHorizontal: 6, color: 'white', fontFamily: 'Helvetica-Bold' },
    colAdm: { width: '20%', paddingHorizontal: 6, color: 'white', fontFamily: 'Helvetica-Bold' },
    colMarks: { width: '14%', paddingHorizontal: 6, color: 'white', fontFamily: 'Helvetica-Bold', textAlign: 'center' },
    colGrade: { width: '18%', paddingHorizontal: 6, color: 'white', fontFamily: 'Helvetica-Bold', textAlign: 'center' },
    cellPos: { width: '10%', paddingHorizontal: 6, fontFamily: 'Helvetica-Bold', color: GREEN },
    cellName: { width: '38%', paddingHorizontal: 6 },
    cellAdm: { width: '20%', paddingHorizontal: 6, color: GRAY_400 },
    cellMarks: { width: '14%', paddingHorizontal: 6, textAlign: 'center', fontFamily: 'Helvetica-Bold' },
    cellGrade: { width: '18%', paddingHorizontal: 6, textAlign: 'center' },
    footer: { position: 'absolute', bottom: 16, left: 32, right: 32, fontSize: 7, color: GRAY_400, textAlign: 'center' },
});

export function ExamResultsPdfDocument({ data }: { data: ExamResultsPdfData }) {
    return (
        <Document>
            <Page size="A4" style={st.page}>
                <Text style={st.schoolName}>{data.schoolName}</Text>
                <Text style={st.docTitle}>{data.examName} — {data.subjectName} ({data.className})</Text>
                <Text style={st.subTitle}>Max Score: {data.maxScore} · Generated {data.generatedAt} · {data.rows.length} student{data.rows.length !== 1 ? 's' : ''}</Text>

                <View style={st.table}>
                    <View style={st.headerRow} fixed>
                        <Text style={st.colPos}>Pos</Text>
                        <Text style={st.colName}>Student Name</Text>
                        <Text style={st.colAdm}>Admission No</Text>
                        <Text style={st.colMarks}>Marks</Text>
                        <Text style={st.colGrade}>Grade</Text>
                    </View>
                    {data.rows.map((r, i) => (
                        <View key={i} style={i % 2 === 1 ? [st.row, st.rowAlt] : st.row} wrap={false}>
                            <Text style={st.cellPos}>{r.position}</Text>
                            <Text style={st.cellName}>{r.studentName}</Text>
                            <Text style={st.cellAdm}>{r.admissionNumber}</Text>
                            <Text style={st.cellMarks}>{r.marks}</Text>
                            <Text style={st.cellGrade}>{r.grade}</Text>
                        </View>
                    ))}
                </View>

                <Text style={st.footer} fixed>Generated by SkulBase — this document reflects results as displayed in the system at the time of export.</Text>
            </Page>
        </Document>
    );
}

export async function generateExamResultsPdf(data: ExamResultsPdfData): Promise<Buffer> {
    return renderToBuffer(<ExamResultsPdfDocument data={data} />);
}
